import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'ress'
import { ClerkProvider } from '@clerk/nextjs'
import Header from '@/components/Header'
import { Toaster } from 'react-hot-toast'
import { NavigationHeader } from '@/components/navigationHeader'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <Toaster />
        <body className={inter.className}>
          <Header />
          <NavigationHeader />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
